### ISSUE TITLE
Outlining Collapse to Definitions conflict

### ISSUE THREAD

**Issue by MoSkinny** [Skybladev2/CSharpOutline2013#2]
First off, thanks for the handy tool! I've found that to tool behaves in an unexpected way with the Outlining - > Collapse to Definitions functionality. It seems that all of the blocks will collapse except for the blocks/outlines added by this tool...those blocks remain open.

Thanks again

**Comment by Skybladev2** [comment]
Thanks for reply!

Many people report this tool breaks this functionality.
Unfortunately, I still can not reproduce it.
Some people have to reinstall extension to make Collapse to Definitions work again. You can try do this too.

**Comment by MoSkinny** [comment]
Reinstalling the extension did the trick! Thanks!!
