### ISSUE TITLE
.cshtml files

### ISSUE THREAD

**Issue by M-Zuber** [Skybladev2/CSharpOutline2013#4]
It seems that this extension does not currently work on `.cshtml` files.
This is a feature that would add a lot I believe.

**Comment by Skybladev2** [comment]
Yeah, I see...
It seems [ContentType("Razor.C#")] attribute does not work in this version of Visual Studio. It works on VS2010 and 2012 though.
This is poorly documented feature and [MSDN](https://msdn.microsoft.com/en-us/library/dd885244.aspx) does not provide much info how to fix my (perfect) code ;)

**Comment by M-Zuber** [comment]
According too `IContentTypeRegistryService.ContentTypes` the correct value is `"Razor"`or `"RazorCSharp"` - at least for 2013
![image](https://cloud.githubusercontent.com/assets/4746537/7748196/005cc43c-ffcb-11e4-9cdf-ce22395f21b3.png)

**Comment by Skybladev2** [comment]
Hmm, this table looks a little different to what I saw.
Thanks a lot, I made a [fix](https://github.com/Skybladev2/CSharpOutline2013/commit/5f74f52bf7f70e5de35e58aabb7a115d669ce99c), will update package in gallery in minutes.

**Comment by M-Zuber** [comment]
Thank you for the quick response. I hope it doesn't break 2010/2012

**Comment by Skybladev2** [comment]
No, there is separate package for every VS version.
Microsoft makes some changes from version to version in their text processor, so (as you can see) it is much easier to maintain each version independently.
