### ISSUE TITLE
Can you add the ability to collapse 'case' statements? (Feature Request)

### ISSUE THREAD

**Issue by howellcc** [Skybladev2/CSharpOutline2013#6]
Can you add the ability to collapse 'case' statements?

**Comment by Skybladev2** [comment]
@howellcc  Sorry for late reply.
No, I have no plans to add this feature.

Current algorithm analyzes braces only. It does not take into account any keywords.
Thus, if you have really big block of code,you can workaround this by adding braces inside the case body, like this:
![untitled](https://cloud.githubusercontent.com/assets/548735/24549434/497a9320-162a-11e7-92b0-f1d88107e281.png)

**Comment by howellcc** [comment]
ok, thanks for the tip.
