### ISSUE TITLE
need .NET 4,7 support for VisualStudio2013 install

### ISSUE THREAD

**Issue by SMokrzyckiHYLAMobile** [Skybladev2/CSharpOutline2013#7]
Cannot install VStudio2013 on Windows 10 machine because it only has .NET 4.7 on the machine.  Can you update the install to support .NET 4.7

**Comment by Skybladev2** [comment]
Done: https://visualstudiogallery.msdn.microsoft.com/6c3c5dec-1534-4c42-81b1-cfd4615fd0e9?redir=0
